### ISSUE TITLE
Error: A BindingEngine must implement parseText

### ISSUE THREAD

**Issue by heruan** [aurelia/dialog#140]
Just cloned `skeleton-navigation/skeleton-es2016`, then
```
$ npm install
$ jspm install
$ jspm install aurelia-dialog
```
then adding `aurelia.use.plugin('aurelia-dialog')` to `main.js` results in
```
aurelia-templating.js:692 Uncaught (in promise) Error: A BindingLanguage must implement parseText(...)
    at BindingLanguage.parseText (http://localhost:9002/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:692:13)
    at ViewCompiler._compileNode (http://localhost:9002/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:2008:79)
    at ViewCompiler._compileNode (http://localhost:9002/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:2028:33)
    at ViewCompiler.compile (http://localhost:9002/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:1985:12)
    at http://localhost:9002/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:2615:49
```

**Comment by doktordirk** [comment]
one does get that with forks at times

**Comment by heruan** [comment]
I have forks, indeed—I think aurelia-dialog isn't ready for the latest skeleton.
