### ISSUE TITLE
VM that extends BaseI18N failing to load as dialog VM

### ISSUE THREAD

**Issue by stefan505** [aurelia/dialog#150]
Example VM to be loaded into modal
```
@autoinject
export class UserSettings extends BaseI18N
{
    public user: IUserOwn;

    constructor(
        private _i18n: I18N,
        private _ea: EventAggregator,
        public controller: DialogController)
    {
        super(_i18n, Element, _ea);
    }

    activate(user: IUserOwn)
    {
        this.user = user;
    }
}
```
When attempting to use `UserSettings` as the `viewModel` for a dialog, the following error occurs:
```
i18n.js:136 Uncaught (in promise) TypeError: el.querySelectorAll is not a function
    at I18N.updateTranslations (http://localhost:52058/jspm_packages/npm/aurelia-i18n@0.5.3/i18n.js:136:22)
    at UserSettings.attached (http://localhost:52058/jspm_packages/npm/aurelia-i18n@0.5.3/base-i18n.js:33:17)
    at Controller.attached (http://localhost:52058/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js:2947:24)
    at View.attached (http://localhost:52058/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js:1016:25)
    at ViewSlot.attached (http://localhost:52058/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js:1472:15)
    at DialogController.dialogController.showDialog (http://localhost:52058/jspm_packages/npm/aurelia-dialog@0.6.1/renderers/dialog-renderer.js:114:31)
    at eval (http://localhost:52058/jspm_packages/npm/aurelia-dialog@0.6.1/renderers/dialog-renderer.js:70:35)
```

**Comment by jedd-ahyoung** [comment]
I think this is just an oversight on our part - we aren't registering the
viewslot element with the child container. I'll mark this as a bug.


2016-05-18 15:01 GMT-04:00 Stefan Buys <notifications@github.com>:

**Comment by jedd-ahyoung** [comment]
This is actually related to https://github.com/aurelia/dialog/issues/15 and I believe it's the same issue. Due to the refactors we've done we can resolve this.
