### ISSUE TITLE
DialogRenderer must implement getDialogContainer()

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/dialog#155]
Trying to implement dialog as per documentation but run into this error that I don't understand why I am getting.

```
renderer.js:21 Uncaught (in promise) Error: DialogRenderer must implement getDialogContainer().
    at Renderer.getDialogContainer (http://localhost:3000/jspm_packages/npm/aurelia-dialog@0.6.1/renderers/renderer.js:21:13)
    at eval (http://localhost:3000/jspm_packages/npm/aurelia-dialog@0.6.1/dialog-service.js:43:80)
    at DialogService.open (http://localhost:3000/jspm_packages/npm/aurelia-dialog@0.6.1/dialog-service.js:33:21)
    at Welcome.addClick (http://localhost:3000/app/welcome/welcome.js:90:40)
    at CallScope.evaluate (http://localhost:3000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.6/aurelia-binding.js:1567:21)
    at Listener.callSource (http://localhost:3000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.6/aurelia-binding.js:4989:42)
    at HTMLButtonElement.eval (http://localhost:3000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.6/aurelia-binding.js:5013:24)getDialogContainer @ renderer.js:21(anonymous function) @ dialog-service.js:43open @ dialog-service.js:33addClick @ welcome.js:23evaluate @ aurelia-binding.js:1567callSource @ aurelia-binding.js:4989(anonymous function) @ aurelia-binding.js:5013
```

**Comment by caperavensoftware** [comment]
initing the plugin as:

```
      .plugin('aurelia-dialog', config => {
          config.useDefaults();
          config.settings.lock = true;
          config.settings.centerHorizontalOnly = false;
          config.settings.startingZIndex = 5;
       });
```

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung Can you look into this?

**Comment by jedd-ahyoung** [comment]
@caperavensoftware Can you recreate this in a Github Gist or a Plunk? Looking at your stack trace, I'm wondering where that `eval` statement in the stack trace is coming from. Additionally, can you tell us which browser you're using? I imagine you're falling back to the AMD distribution, but I want to make sure.

**Comment by jedd-ahyoung** [comment]
@caperavensoftware Are you still running into this issue?

**Comment by pixels4nickels** [comment]
I am running into this issue using the webpack/es6 stack. Here is my stack trace:
```
renderer.js:15 Uncaught (in promise) Error: DialogRenderer must implement getDialogContainer().
    at Renderer.getDialogContainer (webpack:///./~/aurelia-dialog/dist/commonjs/renderer.js?:15:11)
    at eval (webpack:///./~/aurelia-dialog/dist/commonjs/dialog-service.js?:45:44)
    at DialogService.open (webpack:///./~/aurelia-dialog/dist/commonjs/dialog-service.js?:41:19)
    at About.submit (webpack:///./src/about/about.js?:47:28)
    at About.activate (webpack:///./src/about/about.js?:34:14)
    at eval (webpack:///./~/aurelia-router/dist/commonjs/aurelia-router.js?:1200:79)
    at iterate (webpack:///./~/aurelia-router/dist/commonjs/aurelia-router.js?:1206:10)
    at processActivatable (webpack:///./~/aurelia-router/dist/commonjs/aurelia-router.js?:1217:10)
    at ActivateNextStep.run (webpack:///./~/aurelia-router/dist/commonjs/aurelia-router.js?:1098:12)
    at next (webpack:///./~/aurelia-router/dist/commonjs/aurelia-router.js?:133:18)
```

Here is my main configureation:
```
bootstrap(function (aurelia) {
    aurelia.use
        .standardConfiguration()
        .developmentLogging()
        .plugin('aurelia-dialog', config => {
            config.useDefaults();
            config.settings.lock = true;
            config.settings.centerHorizontalOnly = false;
            config.settings.startingZIndex = 5;
        })
        .globalResources("register-project/register-project");
    aurelia.use.plugin('aurelia-binding-functions');
    aurelia.use.plugin('aurelia-rxjs');
    aurelia.start().then(() => aurelia.setRoot('app', document.body));
});
```
And here is the about.js view model that the dialog is spawned from:
```
import {computedFrom, inject} from 'aurelia-framework'
import {DialogService} from 'aurelia-dialog'
import {RegisterProject} from '../register-project/register-project'

@inject(DialogService)
export class About {
    constructor(dialogService) {
        this.dialogService = dialogService;
    }
    activate() {
        this.submit();
    }
    submit() {
        this.dialogService.open({
            viewModel: 'register-project/register-project',
            model: {}
        }).then(response => {
            if (!response.wasCancelled) {
                console.log('good');
            } else {
                console.log('bad');
            }
            console.log(response.output);
        });
    }
}
```

**Comment by pixels4nickels** [comment]
Using the newest webpack skeleton for Javascript language type gives me the same output. I am testing in Chrome and Safari. Safari the error is a bit more obtuse:
```
Unhandled rejection getDialogContainer

_execute
_resolveFromExecutor
Promise
open
submit
evaluate
callSource

handleDelegatedEvent
```

**Comment by jedd-ahyoung** [comment]
I'm not sure why, but looking at the stack trace, the wrong renderer is being loaded. This seems to be a module loader issue (perhaps with webpack) and may be related to this issue (https://github.com/aurelia/dialog/issues/168).

**Comment by EisenbergEffect** [comment]
Closing this since the dialog now has the resources configuration and the new webpack skeletons should read that correctly.

**Comment by kuechlerm** [comment]
This still litters the console if you use the aurelia-cli and run `au test`.
Any chance to avoid that?

**Comment by AStoker** [comment]
@kuechlerm, did you figure out your issue with the test? Just starting to see this on my machine.

**Comment by ajoslin103** [comment]
seeing this with the latest cli-webpack but only in prod...

**Comment by zhhz** [comment]
Same here, I'm seeing it in my console too....

**Comment by RomkeVdMeulen** [comment]
And here...

**Comment by Sayan751** [comment]
@RomkeVdMeulen Can you please share how you loaded aurelia-dialog plugin before the tests? I have tried the following, but without luck.

```javascript
import { bootstrap } from "aurelia-bootstrapper";
import { Aurelia, Container, PLATFORM } from "aurelia-framework";

describe("test specs", () => {
    let container: Container;

    beforeAll(async () => {

        await bootstrap(async (aurelia: Aurelia) => {
            aurelia.use
                .standardConfiguration()
                .developmentLogging()
                .plugin(PLATFORM.moduleName("aurelia-dialog"), (config) => {
                    config.useDefaults();
                    config.settings.lock = true;
                    config.settings.centerHorizontalOnly = false;
                    config.settings.startingZIndex = 5;
                    config.settings.keyboard = true;
                });

            Container.instance = container = new Container();
            aurelia.container = container;
            await aurelia.start();
        });

    });
});
```
On `aurelia.start()` I am geeting the following error.

>Error: Loader must implement loadAllModules(ids).
    at Loader.loadAllModules (webpack-internal:///./node_modules/aurelia-loader/dist/native-modules/aurelia-loader.js:113:11)
    at ViewEngine.importViewResources (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:3593:24)
    at eval (webpack-internal:///aurelia-framework:646:23)
    at \<Jasmine\>
    at loadResources (webpack-internal:///aurelia-framework:637:7)
    at eval (webpack-internal:///aurelia-framework:731:14)
    at next (webpack-internal:///aurelia-framework:577:30)
    at runTasks (webpack-internal:///aurelia-framework:583:10)
    at eval (webpack-internal:///aurelia-framework:936:16)
    at \<Jasmine\>
    at eval (webpack-internal:///aurelia-framework:935:21)
    at \<Jasmine\>
    at FrameworkConfiguration.apply (webpack-internal:///aurelia-framework:919:42)
    at Aurelia.start (webpack-internal:///aurelia-framework:463:37) ...

Thus finally facing 
>Error: DialogRenderer must implement getDialogContainer().

**Comment by RomkeVdMeulen** [comment]
@Sayan751 Sorry, my setup is based on SystemJS, and this seems to be webpack-based.

**Comment by hiaux0** [comment]
Based on the [comment of @Sayan751 ](https://github.com/aurelia/dialog/issues/155#issuecomment-403860488), this solved it for me:
_Note the double arrows `>>` pointing at the interesting part_

``` js
import { getComponent } from 'common/component-testing';
import { bootstrap } from 'aurelia-bootstrapper';
import { PLATFORM } from 'aurelia-pal';

let component;
let element;
let viewModel;

const view = '...';

/**
 * @param {InitialBindings} param.bindings
 */
function create({ bindings }) {
  return component
    .inView(view)
    .boundTo(bindings)
    .create(bootstrap)
    .then(() => {
      ({ element, viewModel } = component);
    });
}

fdescribe('...', () => {
  beforeEach(async () => {
    component = getComponent(PLATFORM.moduleName('...'));
    // Make sure that the aurelia-dialog plugin is loaded
>>  component.bootstrap(async (aurelia) => {
      aurelia.use
        .standardConfiguration()
        .plugin(PLATFORM.moduleName('aurelia-dialog'), (config) => {
          config.useDefaults();
        });
    });
  });
  afterEach(() => { component.dispose(); });

  it('...', async () => {
    await create({ bindings: {} });
  });
});

```

Here, `getComponent` is a wrapper around `StageComponent.withResources` that loads all the text context for us.
