### ISSUE TITLE
Error while using aurelia-dialog

### ISSUE THREAD

**Issue by rzvpopescu** [aurelia/dialog#19]
Hello,

I'm trying to use aurelia-dialog plugin, and if I try the example from the documentation I receive the following error.
I've got the latest aurelia version from gitbub and the error still occurs.

Unhandled promise rejection Error: Error instantiating configure. Check the inner error for details.
You can  check the error at this address : http://notes-popescurazvan.c9.io/
Just hit the Submit button and will see the error in console.
Thanks
------------------------------------------------
inner error: TypeError: Cannot read property 'globalizeResources' of undefined
    at new configure (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dialog@master/index.js:13:12)
    at Object.n.construct (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1980:21)
    at ClassActivator.invoke (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:186:22)
    at Container.invoke (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:399:31)
    at Array.<anonymous> (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:272:44)
    at Container.get (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:329:24)
    at http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:3264:75
    at f (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
------------------------------------------------
inner error: TypeError: Cannot read property 'globalizeResources' of undefined
    at new configure (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dialog@master/index.js:13:12)
    at Object.n.construct (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1980:21)
    at ClassActivator.invoke (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:186:22)
    at Container.invoke (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:399:31)
    at Array.<anonymous> (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:272:44)
    at Container.get (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:329:24)
    at http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:3264:75
    at f (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at Object.AggregateError (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/logging@0.6.4/aurelia-logging.js:24:15)
    at Container.invoke (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:409:31)
    at Array.<anonymous> (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:272:44)
    at Container.get (http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:329:24)
    at http://notes-popescurazvan.c9.io/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:3264:75
    at f (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at Number.f (http://notes-popescurazvan.c9.io/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1596:24)

**Comment by PWKad** [comment]
Sounds like you are using a version before the configuration API was refactored.  Since this repo has not been released yet officially just `jspm install` it from master again.

**Comment by michaelmalonenz** [comment]
It's due to the fact that even though the code has been updated, the build (in the repository) doesn't match what's there, so it's trying to use the old API.

**Comment by rzvpopescu** [comment]
I see. So are you planning to fix this issue ? Thanks

**Comment by michaelmalonenz** [comment]
@rzvpopescu You should be (in the interim) be able to use our fork, which will be kept up-to-date until this aurelia-dialog is released, here: https://github.com/drivesoftware/dialog/releases/tag/0.1.1

**Comment by PWKad** [comment]
I've committed the proper `dist` files to update.  I've also made the initial release, so please let me know if you are running in to any issues.
