### ISSUE TITLE
default model failing to load

### ISSUE THREAD

**Issue by samelamin** [aurelia/dialog#26]
I am trying to create a reusable dialog for users to confirm whether they want to do something or not

to do this I am creating a custom element, but how do I know when the confirm button on my custom element is clicked?
 

To solve this problem I am hoping to use this repo but I am getting this error when loading the default example

ex = Error: Loaders must implement loadModule(id). at Loader.loadModule

**Comment by ShawnCholeva** [comment]
I also am running into the same error.  It was working earlier, then I pulled down a commit from my buddy who may have been on a different version, and this error began to happen.  I am using the demonstration on the github page using a viewModel (it also is the same error with the Prompt).

```
Error: Loaders must implement loadModule(id).
    at Loader.loadModule (http://localhost:20936/jspm_packages/github/aurelia/loader@0.9.0/aurelia-loader.js:103:13)
    at ViewEngine.importViewModelResource (http://localhost:20936/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:2352:26)
    at CompositionEngine.createViewModel (http://localhost:20936/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3677:30)
    at DialogService._getViewModel (http://localhost:20936/jspm_packages/github/aurelia/dialog@0.2.1/dialog-service.js:32:47)
    at DialogService.open (http://localhost:20936/jspm_packages/github/aurelia/dialog@0.2.1/dialog-service.js:55:30)
    at new Promise (http://localhost:20936/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:193:9)
    at DialogService.open (http://localhost:20936/jspm_packages/github/aurelia/dialog@0.2.1/dialog-service.js:43:20)
    at ModalService.submit (http://localhost:20936/resources/modal.js!eval:32:44)
    at List.editItem (http://localhost:20936/clinics/list.js!eval:43:36)
    at CallScope.evaluate (http://localhost:20936/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:1310:54)
```

**Comment by EisenbergEffect** [comment]
This isn't a bug related to the dialog plugin. I would ask this question in the gitter. The error indicates that you don't have the framework properly configured somehow. Perhaps you have version conflicts causing incorrect loading.
