### ISSUE TITLE
Error on the plugin declaration

### ISSUE THREAD

**Issue by LivesleyWA** [aurelia/dialog#42]
V0.4.1. - Errors disappears if  _.plugin("aurelia-dialog")_ is removed.

_Declaration_

  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin("aurelia-dialog")
    .plugin("aurelia-flux");

_SystemJS declaration_

    "github:aurelia/dialog@0.4.1": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.11.0",
      "aurelia-framework": "github:aurelia/framework@0.17.0",
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-templating": "github:aurelia/templating@0.16.0",
      "text": "github:systemjs/plugin-text@0.0.2"
    },

_Error_

Unhandled promise rejection TypeError: Cannot read property 'endsWith' of undefined
    at Function.convertModuleIdToViewUrl (http://localhost:50082/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:408:24)
    at new ConventionalViewStrategy (http://localhost:50082/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:399:47)
    at Function.getDefault (http://localhost:50082/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:344:20)
    at HtmlBehaviorResource.load (http://localhost:50082/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3174:74)
    at ResourceDescription.load (http://localhost:50082/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3319:25)
    at ResourceModule.load (http://localhost:50082/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3259:33)
    at http://localhost:50082/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:2407:43
    at run (http://localhost:50082/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:50082/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:50082/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:50082/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:50082/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:50082/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)

**Comment by Mule52** [comment]
I am getting this same error. I have installed 0.4.1, "Up to date - aurelia-dialog as github:aurelia/dialog@^0.4.1 (0.4.1)"

When I uncomment the line registering the plugin below, it no longer receive the error.

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-dialog'); // uncommenting this line no longer results in an error
  aurelia.start().then(a => a.setRoot());
}



Unhandled promise rejection TypeError: Cannot read property 'endsWith' of undefined
    at Function.convertModuleIdToViewUrl (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:408:24)
    at new ConventionalViewStrategy (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:399:47)
    at Function.getDefault (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:344:20)
    at HtmlBehaviorResource.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3174:74)
    at ResourceDescription.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3319:25)
    at ResourceModule.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3259:33)
    at http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:2407:43
    at f (http://localhost:8080/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:8080/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:8080/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
shim.min.js:1444 Unhandled promise rejection TypeError: Cannot read property 'endsWith' of undefined
    at Function.convertModuleIdToViewUrl (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:408:24)
    at new ConventionalViewStrategy (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:399:47)
    at Function.getDefault (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:344:20)
    at HtmlBehaviorResource.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3174:74)
    at ResourceDescription.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3319:25)
    at ResourceModule.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3259:33)
    at http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:2407:43
    at f (http://localhost:8080/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:8080/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:8080/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
shim.min.js:1444 Unhandled promise rejection TypeError: Cannot read property 'endsWith' of undefined
    at Function.convertModuleIdToViewUrl (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:408:24)
    at new ConventionalViewStrategy (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:399:47)
    at Function.getDefault (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:344:20)
    at HtmlBehaviorResource.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3174:74)
    at ResourceDescription.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3319:25)
    at ResourceModule.load (http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3259:33)
    at http://localhost:8080/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:2407:43
    at f (http://localhost:8080/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)

**Comment by Mule52** [comment]
This can be fixed by getting all of the latest updates for jspm dependencies (config.js). Once I did that, I no longer have this issue.

**Comment by LivesleyWA** [comment]
This may be fixed as suggested by Mule52. I updated the jspm install and I no longer receive the error. Sadly, I am now receiving other errors but not to do with this module.

**Comment by Mule52** [comment]
What errors are you receiving? You may be receiving all the same ones I was. 

I had to update all of the dependencies in my config.js under the map section, for each one - jspm aurelia-framework... etc. Then jspm update. I was having issues with too many forks that were relying on older libraries. You want the latest, and for me bootstrap was stuck on 16.0.

**Comment by LivesleyWA** [comment]
I raised the issue https://github.com/aurelia/router/issues/228 which has the details. If you have a working system.config or other list of versions that work I would be interested to see them. I can also work through to see which is the latest version of each aurelia module.

Seems a little unstable right now which is a bit frustrating but that is the nature of beta releases I suppose!

**Comment by Mule52** [comment]
Subject to change... 
https://github.com/Mule52/spring-boot-demo/blob/master/src/main/webapp/config.js

**Comment by LivesleyWA** [comment]
Thanks - I'll give it a try

**Comment by PWKad** [comment]
Closing - you need to use the latest versions of Aurelia to use the latest releases.  This should ease up a bit after v1.

**Comment by SivaJonnala** [comment]
Cannot read property 'endsWith' of undefined, This error is coming when I was using plugin aurelia-dialog. Please fix this issue as soon as possible.........
