### ISSUE TITLE
Dialog Plugin Broken in latest release

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/dialog#48]
If i include this line in main.js
    `.plugin('aurelia-dialog') `

my app won't load and i get the exception

Unhandled promise rejection TypeError: Cannot read property 'endsWith' of undefined
    at Function.convertModuleIdToViewUrl (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:408:24)
    at new ConventionalViewStrategy (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:399:47)
    at Function.getDefault (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:344:20)
    at HtmlBehaviorResource.load (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3174:74)
    at ResourceDescription.load (http://localhost:9000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3319:25)
    at ResourceModule.load (http://localhost:9000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3259:33)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:2407:43
    at f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)

**Comment by EisenbergEffect** [comment]
We will need a repro for this.

**Comment by devteamexpress** [comment]
Seems to be this was as a result of packages not being properly updated through JSPM, after reinstalling all packages again it worked perfectly
